image: Visual Studio 2017

build_script:
  - dotnet build -c release

test_script:
  - cd MarbleTest.Net.Test
  - dotnet test

after_build:
  - dotnet publish MarbleTest.Net.DeepComparer -c release -o %appveyor_build_folder%\dist
