image: Visual Studio 2017
build:
  project: MarbleTest.Net.sln
before_build:
  - dotnet clean  
  - dotnet restore
build_script:
  - dotnet build
test_script:
  - cd MarbleTest.Net.Test
  - dotnet test