build:
  project: MarbleTest.Net.sln
before_build:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.1.0/nuget.exe
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore
