image: Visual Studio 2019

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

build_script:
  - dotnet restore
  - dotnet build -c release

test_script:
  - cd MarbleTest.Net.Test
  - dotnet test

after_test:
  - cd ..
  - dotnet pack MarbleTest.Net -c release -o %appveyor_build_folder%\dist

artifacts:
  path: dist\*.nupkg
  name: nuget

deploy:
  provider: NuGet
  api_key:
    secure: eZfmf6WPntyOjPsMFVUdite2ajDpLw7K/eK8fuCU13ZtBOacAgUazFlAwbHWQPXb
  skip_symbols: true